### ISSUE TITLE
Python not working for me

### ISSUE THREAD

**Issue by neo305** [Zer0xFF/PS4_db_rebuilder#19]
what am I doing wrong please?

PS C:\Users\laz30\Desktop\release_0.1> py fix_db.py 10.12.1.112
Traceback (most recent call last):
  File "C:\Users\laz30\Desktop\release_0.1\fix_db.py", line 51, in <module>
    ftp.connect(PS4_IP, 1337, timeout=30)
  File "C:\Users\laz30\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 158, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "C:\Users\laz30\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\laz30\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
PS C:\Users\laz30\Desktop\release_0.1>

**Comment by Pharaoh2k** [comment]
Use Itemzflow, which works better than any script:
https://github.com/LightningMods/Itemzflow
